/*
 * *****************************************************************************
 * Copyright (C) 2014-2024 Dennis Sheirer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 * ****************************************************************************
 */

// Generated by jextract

package io.github.dsheirer.source.tuner.sdrplay.api.v3_08;

import java.lang.foreign.Arena;
import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfFloat;

/**
 * {@snippet lang=c :
 * struct {
 *     float curr;
 *     float max;
 *     float min;
 * }
 * }
 */
public class sdrplay_api_GainValuesT {

    sdrplay_api_GainValuesT() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        sdrplay_api_h.C_FLOAT.withName("curr"),
        sdrplay_api_h.C_FLOAT.withName("max"),
        sdrplay_api_h.C_FLOAT.withName("min")
    ).withName("$anon$53:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfFloat curr$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("curr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float curr
     * }
     */
    public static final OfFloat curr$layout() {
        return curr$LAYOUT;
    }

    private static final long curr$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float curr
     * }
     */
    public static final long curr$offset() {
        return curr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float curr
     * }
     */
    public static float curr(MemorySegment struct) {
        return struct.get(curr$LAYOUT, curr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float curr
     * }
     */
    public static void curr(MemorySegment struct, float fieldValue) {
        struct.set(curr$LAYOUT, curr$OFFSET, fieldValue);
    }

    private static final OfFloat max$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("max"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float max
     * }
     */
    public static final OfFloat max$layout() {
        return max$LAYOUT;
    }

    private static final long max$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float max
     * }
     */
    public static final long max$offset() {
        return max$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float max
     * }
     */
    public static float max(MemorySegment struct) {
        return struct.get(max$LAYOUT, max$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float max
     * }
     */
    public static void max(MemorySegment struct, float fieldValue) {
        struct.set(max$LAYOUT, max$OFFSET, fieldValue);
    }

    private static final OfFloat min$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("min"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float min
     * }
     */
    public static final OfFloat min$layout() {
        return min$LAYOUT;
    }

    private static final long min$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float min
     * }
     */
    public static final long min$offset() {
        return min$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float min
     * }
     */
    public static float min(MemorySegment struct) {
        return struct.get(min$LAYOUT, min$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float min
     * }
     */
    public static void min(MemorySegment struct, float fieldValue) {
        struct.set(min$LAYOUT, min$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

