/*
 * *****************************************************************************
 * Copyright (C) 2014-2023 Dennis Sheirer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 * ****************************************************************************
 */

// Generated by jextract

package io.github.dsheirer.source.tuner.sdrplay.api.v3_08;

import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;
import java.lang.foreign.SegmentScope;
import java.lang.foreign.StructLayout;
import java.lang.invoke.VarHandle;

/**
 * {@snippet :
 * struct {
 *     unsigned int gRdB;
 *     unsigned int lnaGRdB;
 *     double currGain;
 * };
 * }
 */
public class sdrplay_api_GainCbParamT {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("gRdB"),
        Constants$root.C_INT$LAYOUT.withName("lnaGRdB"),
        Constants$root.C_DOUBLE$LAYOUT.withName("currGain")
    );
    public static MemoryLayout $LAYOUT() {
        return sdrplay_api_GainCbParamT.$struct$LAYOUT;
    }
    static final VarHandle gRdB$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("gRdB"));
    public static VarHandle gRdB$VH() {
        return sdrplay_api_GainCbParamT.gRdB$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int gRdB;
     * }
     */
    public static int gRdB$get(MemorySegment seg) {
        return (int)sdrplay_api_GainCbParamT.gRdB$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int gRdB;
     * }
     */
    public static void gRdB$set(MemorySegment seg, int x) {
        sdrplay_api_GainCbParamT.gRdB$VH.set(seg, x);
    }
    public static int gRdB$get(MemorySegment seg, long index) {
        return (int)sdrplay_api_GainCbParamT.gRdB$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void gRdB$set(MemorySegment seg, long index, int x) {
        sdrplay_api_GainCbParamT.gRdB$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle lnaGRdB$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("lnaGRdB"));
    public static VarHandle lnaGRdB$VH() {
        return sdrplay_api_GainCbParamT.lnaGRdB$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int lnaGRdB;
     * }
     */
    public static int lnaGRdB$get(MemorySegment seg) {
        return (int)sdrplay_api_GainCbParamT.lnaGRdB$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int lnaGRdB;
     * }
     */
    public static void lnaGRdB$set(MemorySegment seg, int x) {
        sdrplay_api_GainCbParamT.lnaGRdB$VH.set(seg, x);
    }
    public static int lnaGRdB$get(MemorySegment seg, long index) {
        return (int)sdrplay_api_GainCbParamT.lnaGRdB$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void lnaGRdB$set(MemorySegment seg, long index, int x) {
        sdrplay_api_GainCbParamT.lnaGRdB$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle currGain$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("currGain"));
    public static VarHandle currGain$VH() {
        return sdrplay_api_GainCbParamT.currGain$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double currGain;
     * }
     */
    public static double currGain$get(MemorySegment seg) {
        return (double)sdrplay_api_GainCbParamT.currGain$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double currGain;
     * }
     */
    public static void currGain$set(MemorySegment seg, double x) {
        sdrplay_api_GainCbParamT.currGain$VH.set(seg, x);
    }
    public static double currGain$get(MemorySegment seg, long index) {
        return (double)sdrplay_api_GainCbParamT.currGain$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void currGain$set(MemorySegment seg, long index, double x) {
        sdrplay_api_GainCbParamT.currGain$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


