/*
 * *****************************************************************************
 * Copyright (C) 2014-2024 Dennis Sheirer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 * ****************************************************************************
 */

// Generated by jextract

package io.github.dsheirer.source.tuner.sdrplay.api.v3_14;

import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;
import java.lang.foreign.SegmentScope;
import java.lang.foreign.StructLayout;
import java.lang.invoke.VarHandle;
/**
 * {@snippet :
 * struct {
 *     unsigned int sampleNum;
 *     unsigned int period;
 * };
 * }
 */
public class sdrplay_api_SyncUpdateT {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("sampleNum"),
        Constants$root.C_INT$LAYOUT.withName("period")
    );
    public static MemoryLayout $LAYOUT() {
        return sdrplay_api_SyncUpdateT.$struct$LAYOUT;
    }
    static final VarHandle sampleNum$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("sampleNum"));
    public static VarHandle sampleNum$VH() {
        return sdrplay_api_SyncUpdateT.sampleNum$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int sampleNum;
     * }
     */
    public static int sampleNum$get(MemorySegment seg) {
        return (int)sdrplay_api_SyncUpdateT.sampleNum$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int sampleNum;
     * }
     */
    public static void sampleNum$set(MemorySegment seg, int x) {
        sdrplay_api_SyncUpdateT.sampleNum$VH.set(seg, x);
    }
    public static int sampleNum$get(MemorySegment seg, long index) {
        return (int)sdrplay_api_SyncUpdateT.sampleNum$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sampleNum$set(MemorySegment seg, long index, int x) {
        sdrplay_api_SyncUpdateT.sampleNum$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle period$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("period"));
    public static VarHandle period$VH() {
        return sdrplay_api_SyncUpdateT.period$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int period;
     * }
     */
    public static int period$get(MemorySegment seg) {
        return (int)sdrplay_api_SyncUpdateT.period$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int period;
     * }
     */
    public static void period$set(MemorySegment seg, int x) {
        sdrplay_api_SyncUpdateT.period$VH.set(seg, x);
    }
    public static int period$get(MemorySegment seg, long index) {
        return (int)sdrplay_api_SyncUpdateT.period$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void period$set(MemorySegment seg, long index, int x) {
        sdrplay_api_SyncUpdateT.period$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


