blank_issues_enabled: false
contact_links:
  - name: sdrtrunk Support and User Questions - How Do I ...?
    url: https://github.com/DSheirer/sdrtrunk/wiki/Support
    about: Please ask your user questions here -- DO NOT create an issue if you have a user question please!!
