package module.decode.state;

public enum ChangedAttribute
{
	AUDIO_TYPE,
    CHANNEL_NUMBER,
    CHANNEL_NAME,
    CHANNEL_SITE_NUMBER,
    CHANNEL_SITE_NUMBER_ALIAS,
    CHANNEL_STATE,
    DESCRIPTION,
    FROM_TALKGROUP,
    FROM_TALKGROUP_ALIAS,
    FROM_TALKGROUP_TYPE,
    MESSAGE,
    MESSAGE_TYPE,
    NAC,
    SITE,
    SITE_ALIAS,
    SITE_NAME,
    SOURCE,
    SYSTEM,
    SYSTEM_NAME,
    SQUELCH,
    TO_TALKGROUP,
    TO_TALKGROUP_ALIAS,
    TO_TALKGROUP_TYPE,
    WACN;
}