// Generated by jextract

package com.github.dsheirer.sdrplay.api.v3_07;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;
class constants$8 {

    static final FunctionDescriptor sdrplay_api_SelectDevice$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sdrplay_api_SelectDevice$MH = RuntimeHelper.downcallHandle(
        "sdrplay_api_SelectDevice",
        constants$8.sdrplay_api_SelectDevice$FUNC
    );
    static final FunctionDescriptor sdrplay_api_ReleaseDevice$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sdrplay_api_ReleaseDevice$MH = RuntimeHelper.downcallHandle(
        "sdrplay_api_ReleaseDevice",
        constants$8.sdrplay_api_ReleaseDevice$FUNC
    );
    static final FunctionDescriptor sdrplay_api_GetErrorString$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle sdrplay_api_GetErrorString$MH = RuntimeHelper.downcallHandle(
        "sdrplay_api_GetErrorString",
        constants$8.sdrplay_api_GetErrorString$FUNC
    );
    static final FunctionDescriptor sdrplay_api_GetLastError$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sdrplay_api_GetLastError$MH = RuntimeHelper.downcallHandle(
        "sdrplay_api_GetLastError",
        constants$8.sdrplay_api_GetLastError$FUNC
    );
    static final FunctionDescriptor sdrplay_api_DisableHeartbeat$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle sdrplay_api_DisableHeartbeat$MH = RuntimeHelper.downcallHandle(
        "sdrplay_api_DisableHeartbeat",
        constants$8.sdrplay_api_DisableHeartbeat$FUNC
    );
    static final FunctionDescriptor sdrplay_api_DebugEnable$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle sdrplay_api_DebugEnable$MH = RuntimeHelper.downcallHandle(
        "sdrplay_api_DebugEnable",
        constants$8.sdrplay_api_DebugEnable$FUNC
    );
}


