// Generated by jextract

package com.github.dsheirer.sdrplay.api.v3_07;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;
class constants$7 {

    static final FunctionDescriptor sdrplay_api_Open$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle sdrplay_api_Open$MH = RuntimeHelper.downcallHandle(
        "sdrplay_api_Open",
        constants$7.sdrplay_api_Open$FUNC
    );
    static final FunctionDescriptor sdrplay_api_Close$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle sdrplay_api_Close$MH = RuntimeHelper.downcallHandle(
        "sdrplay_api_Close",
        constants$7.sdrplay_api_Close$FUNC
    );
    static final FunctionDescriptor sdrplay_api_ApiVersion$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sdrplay_api_ApiVersion$MH = RuntimeHelper.downcallHandle(
        "sdrplay_api_ApiVersion",
        constants$7.sdrplay_api_ApiVersion$FUNC
    );
    static final FunctionDescriptor sdrplay_api_LockDeviceApi$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle sdrplay_api_LockDeviceApi$MH = RuntimeHelper.downcallHandle(
        "sdrplay_api_LockDeviceApi",
        constants$7.sdrplay_api_LockDeviceApi$FUNC
    );
    static final FunctionDescriptor sdrplay_api_UnlockDeviceApi$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle sdrplay_api_UnlockDeviceApi$MH = RuntimeHelper.downcallHandle(
        "sdrplay_api_UnlockDeviceApi",
        constants$7.sdrplay_api_UnlockDeviceApi$FUNC
    );
    static final FunctionDescriptor sdrplay_api_GetDevices$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle sdrplay_api_GetDevices$MH = RuntimeHelper.downcallHandle(
        "sdrplay_api_GetDevices",
        constants$7.sdrplay_api_GetDevices$FUNC
    );
}


