// Generated by jextract

package com.github.dsheirer.sdrplay.api.v3_07;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryAddress;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.MemorySession;
import java.lang.foreign.SegmentAllocator;
import java.lang.invoke.VarHandle;
public class sdrplay_api_DcOffsetT {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_CHAR$LAYOUT.withName("DCenable"),
        Constants$root.C_CHAR$LAYOUT.withName("IQenable")
    );
    public static MemoryLayout $LAYOUT() {
        return sdrplay_api_DcOffsetT.$struct$LAYOUT;
    }
    static final VarHandle DCenable$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("DCenable"));
    public static VarHandle DCenable$VH() {
        return sdrplay_api_DcOffsetT.DCenable$VH;
    }
    public static byte DCenable$get(MemorySegment seg) {
        return (byte)sdrplay_api_DcOffsetT.DCenable$VH.get(seg);
    }
    public static void DCenable$set( MemorySegment seg, byte x) {
        sdrplay_api_DcOffsetT.DCenable$VH.set(seg, x);
    }
    public static byte DCenable$get(MemorySegment seg, long index) {
        return (byte)sdrplay_api_DcOffsetT.DCenable$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void DCenable$set(MemorySegment seg, long index, byte x) {
        sdrplay_api_DcOffsetT.DCenable$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle IQenable$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("IQenable"));
    public static VarHandle IQenable$VH() {
        return sdrplay_api_DcOffsetT.IQenable$VH;
    }
    public static byte IQenable$get(MemorySegment seg) {
        return (byte)sdrplay_api_DcOffsetT.IQenable$VH.get(seg);
    }
    public static void IQenable$set( MemorySegment seg, byte x) {
        sdrplay_api_DcOffsetT.IQenable$VH.set(seg, x);
    }
    public static byte IQenable$get(MemorySegment seg, long index) {
        return (byte)sdrplay_api_DcOffsetT.IQenable$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void IQenable$set(MemorySegment seg, long index, byte x) {
        sdrplay_api_DcOffsetT.IQenable$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


