// Generated by jextract

package com.github.dsheirer.sdrplay.api.v3_07;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryAddress;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.MemorySession;
import java.lang.foreign.SegmentAllocator;
import java.lang.invoke.VarHandle;
public class sdrplay_api_Rsp2ParamsT {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_CHAR$LAYOUT.withName("extRefOutputEn")
    );
    public static MemoryLayout $LAYOUT() {
        return sdrplay_api_Rsp2ParamsT.$struct$LAYOUT;
    }
    static final VarHandle extRefOutputEn$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("extRefOutputEn"));
    public static VarHandle extRefOutputEn$VH() {
        return sdrplay_api_Rsp2ParamsT.extRefOutputEn$VH;
    }
    public static byte extRefOutputEn$get(MemorySegment seg) {
        return (byte)sdrplay_api_Rsp2ParamsT.extRefOutputEn$VH.get(seg);
    }
    public static void extRefOutputEn$set( MemorySegment seg, byte x) {
        sdrplay_api_Rsp2ParamsT.extRefOutputEn$VH.set(seg, x);
    }
    public static byte extRefOutputEn$get(MemorySegment seg, long index) {
        return (byte)sdrplay_api_Rsp2ParamsT.extRefOutputEn$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void extRefOutputEn$set(MemorySegment seg, long index, byte x) {
        sdrplay_api_Rsp2ParamsT.extRefOutputEn$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


