# Build and publish releases for Linux, Mac, and Windows
name: Nightly Release

on:
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25 (Liberica Full with JavaFX)
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'liberica'
          java-package: 'jdk+fx'

      - name: Build Linux and Mac releases
        uses: gradle/gradle-build-action@v2
        with:
          arguments: runtimeZipOthers -PprojectVersion=0.6.2-beta-1-buns-eastern

      - name: Build Windows release
        uses: gradle/gradle-build-action@v2
        with:
          arguments: runtimeZipWindows -PprojectVersion=0.6.2-beta-1-buns-eastern

      - name: Create build info file
        run: |
          echo -e "ref: $GITHUB_REF \ncommit: $GITHUB_SHA\nbuild: $(date +"%Y-%m-%dT%H:%M:%SZ")" > build/image/build_info.txt

      - name: Publish to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.6.2-beta-1-buns-eastern
          name: v0.6.2-beta-1-buns-eastern
          prerelease: true
          files: |
            build/image/*.zip
            build/image/build_info.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
